---
# "ignoreip" can be an IP address, a CIDR mask or a DNS host
fail2ban_config_ignoreip: 127.0.0.1/8
fail2ban_config_bantime: 600
fail2ban_config_maxretry: 4
fail2ban_config_destemail: root@localhost

# Jails
fail2ban_config_jail_ssh_enabled: yes
fail2ban_config_jail_ssh_ddos_enabled: yes
